/* tslint:disable */
/* eslint-disable */
/**
 * Stripe Payment Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreatePlanDto {
    'name': string;
    /**
     * Amount in smallest currency unit (cents)
     */
    'amount': number;
    'currency': string;
    'interval': CreatePlanDtoIntervalEnum;
}

export const CreatePlanDtoIntervalEnum = {
    Month: 'month',
    Year: 'year',
} as const;

export type CreatePlanDtoIntervalEnum = typeof CreatePlanDtoIntervalEnum[keyof typeof CreatePlanDtoIntervalEnum];


