/* tslint:disable */
/* eslint-disable */
/**
 * Stripe Payment Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreatePaymentDto {
    /**
     * Local customer id (UUID)
     */
    'customerId': string;
    /**
     * Amount in smallest currency unit (cents)
     */
    'amount': number;
    'currency': string;
    /**
     * Pass the same key on retries to guarantee the charge is created at most once
     */
    'idempotencyKey'?: string;
}

