/* tslint:disable */
/* eslint-disable */
/**
 * Stripe Payment Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateSubscriptionDto {
    /**
     * Local customer id (UUID)
     */
    'customerId': string;
    /**
     * Local plan id (UUID)
     */
    'planId': string;
    /**
     * Free trial length in days — Stripe schedules the first charge
     */
    'trialPeriodDays'?: number;
    /**
     * Pass the same key on retries to guarantee the subscription is created at most once
     */
    'idempotencyKey'?: string;
}

