/* tslint:disable */
/* eslint-disable */
/**
 * Stripe Payment Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HealthCheck200ResponseInfoValue } from './health-check200-response-info-value';

export interface HealthCheck200Response {
    'status'?: string;
    'info'?: { [key: string]: HealthCheck200ResponseInfoValue; } | null;
    'error'?: { [key: string]: HealthCheck200ResponseInfoValue; } | null;
    'details'?: { [key: string]: HealthCheck200ResponseInfoValue; };
}

