/* tslint:disable */
/* eslint-disable */
/**
 * Stripe Payment Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Invoice {
    'id': string;
    'stripeInvoiceId': string;
    'customerId': string | null;
    'stripeCustomerId': string | null;
    'stripeSubscriptionId': string | null;
    'amountDue': number;
    'amountPaid': number;
    'currency': string;
    'status': string;
    'hostedInvoiceUrl': string | null;
    'createdAt': string;
    'updatedAt': string;
}

