/* tslint:disable */
/* eslint-disable */
/**
 * Stripe Payment Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Payment {
    'id': string;
    'stripePaymentIntentId': string;
    'customerId': string;
    /**
     * Smallest currency unit (cents)
     */
    'amount': number;
    'currency': string;
    'status': PaymentStatusEnum;
    'createdAt': string;
    'updatedAt': string;
}

export const PaymentStatusEnum = {
    RequiresPaymentMethod: 'requires_payment_method',
    RequiresConfirmation: 'requires_confirmation',
    RequiresAction: 'requires_action',
    Processing: 'processing',
    Succeeded: 'succeeded',
    Canceled: 'canceled',
    Refunded: 'refunded',
} as const;

export type PaymentStatusEnum = typeof PaymentStatusEnum[keyof typeof PaymentStatusEnum];


