/* tslint:disable */
/* eslint-disable */
/**
 * Stripe Payment Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Plan {
    'id': string;
    'stripeProductId': string;
    'stripePriceId': string;
    'name': string;
    /**
     * Smallest currency unit (cents) — never floating point
     */
    'amount': number;
    'currency': string;
    'interval': PlanIntervalEnum;
    'active': boolean;
    'createdAt': string;
    'updatedAt': string;
}

export const PlanIntervalEnum = {
    Year: 'year',
    Month: 'month',
} as const;

export type PlanIntervalEnum = typeof PlanIntervalEnum[keyof typeof PlanIntervalEnum];


