/* tslint:disable */
/* eslint-disable */
/**
 * Stripe Payment Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Subscription {
    'id': string;
    'stripeSubscriptionId': string;
    'customerId': string;
    'planId': string;
    'status': SubscriptionStatusEnum;
    'currentPeriodStart': string | null;
    'currentPeriodEnd': string | null;
    'trialEnd': string | null;
    'createdAt': string;
    'updatedAt': string;
}

export const SubscriptionStatusEnum = {
    Active: 'active',
    Canceled: 'canceled',
    Incomplete: 'incomplete',
    IncompleteExpired: 'incomplete_expired',
    Trialing: 'trialing',
    PastDue: 'past_due',
    Unpaid: 'unpaid',
} as const;

export type SubscriptionStatusEnum = typeof SubscriptionStatusEnum[keyof typeof SubscriptionStatusEnum];


