/* tslint:disable */
/* eslint-disable */
/**
 * Stripe Payment Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateSubscriptionDto } from '../models';
// @ts-ignore
import type { CreateSubscriptionResult } from '../models';
// @ts-ignore
import type { Subscription } from '../models';
// @ts-ignore
import type { SubscriptionList } from '../models';
/**
 * SubscriptionsApi - axios parameter creator
 */
export const SubscriptionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Cancel a subscription immediately
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscriptionsCancel: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('subscriptionsCancel', 'id', id)
            const localVarPath = `/api/v1/subscriptions/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication x-api-key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a subscription (first charge confirmed by frontend)
         * @param {CreateSubscriptionDto} createSubscriptionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscriptionsCreate: async (createSubscriptionDto: CreateSubscriptionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createSubscriptionDto' is not null or undefined
            assertParamExists('subscriptionsCreate', 'createSubscriptionDto', createSubscriptionDto)
            const localVarPath = `/api/v1/subscriptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication x-api-key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSubscriptionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a subscription
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscriptionsGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('subscriptionsGet', 'id', id)
            const localVarPath = `/api/v1/subscriptions/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication x-api-key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List subscriptions, optionally by customer
         * @param {string} [customerId] 
         * @param {any} [limit] 
         * @param {any} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscriptionsList: async (customerId?: string, limit?: any, page?: any, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/subscriptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication x-api-key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            if (customerId !== undefined) {
                localVarQueryParameter['customerId'] = customerId;
            }

            if (limit !== undefined) {
                for (const [key, value] of Object.entries(limit)) {
                    localVarQueryParameter[key] = value;
                }
            }

            if (page !== undefined) {
                for (const [key, value] of Object.entries(page)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SubscriptionsApi - functional programming interface
 */
export const SubscriptionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SubscriptionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Cancel a subscription immediately
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async subscriptionsCancel(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subscriptionsCancel(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.subscriptionsCancel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a subscription (first charge confirmed by frontend)
         * @param {CreateSubscriptionDto} createSubscriptionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async subscriptionsCreate(createSubscriptionDto: CreateSubscriptionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateSubscriptionResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subscriptionsCreate(createSubscriptionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.subscriptionsCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a subscription
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async subscriptionsGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subscriptionsGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.subscriptionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List subscriptions, optionally by customer
         * @param {string} [customerId] 
         * @param {any} [limit] 
         * @param {any} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async subscriptionsList(customerId?: string, limit?: any, page?: any, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subscriptionsList(customerId, limit, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.subscriptionsList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SubscriptionsApi - factory interface
 */
export const SubscriptionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SubscriptionsApiFp(configuration)
    return {
        /**
         * 
         * @summary Cancel a subscription immediately
         * @param {SubscriptionsApiSubscriptionsCancelRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscriptionsCancel(requestParameters: SubscriptionsApiSubscriptionsCancelRequest, options?: RawAxiosRequestConfig): AxiosPromise<Subscription> {
            return localVarFp.subscriptionsCancel(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a subscription (first charge confirmed by frontend)
         * @param {SubscriptionsApiSubscriptionsCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscriptionsCreate(requestParameters: SubscriptionsApiSubscriptionsCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateSubscriptionResult> {
            return localVarFp.subscriptionsCreate(requestParameters.createSubscriptionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a subscription
         * @param {SubscriptionsApiSubscriptionsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscriptionsGet(requestParameters: SubscriptionsApiSubscriptionsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Subscription> {
            return localVarFp.subscriptionsGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List subscriptions, optionally by customer
         * @param {SubscriptionsApiSubscriptionsListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscriptionsList(requestParameters: SubscriptionsApiSubscriptionsListRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionList> {
            return localVarFp.subscriptionsList(requestParameters.customerId, requestParameters.limit, requestParameters.page, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SubscriptionsApi - interface
 */
export interface SubscriptionsApiInterface {
    /**
     * 
     * @summary Cancel a subscription immediately
     * @param {SubscriptionsApiSubscriptionsCancelRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    subscriptionsCancel(requestParameters: SubscriptionsApiSubscriptionsCancelRequest, options?: RawAxiosRequestConfig): AxiosPromise<Subscription>;

    /**
     * 
     * @summary Create a subscription (first charge confirmed by frontend)
     * @param {SubscriptionsApiSubscriptionsCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    subscriptionsCreate(requestParameters: SubscriptionsApiSubscriptionsCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateSubscriptionResult>;

    /**
     * 
     * @summary Get a subscription
     * @param {SubscriptionsApiSubscriptionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    subscriptionsGet(requestParameters: SubscriptionsApiSubscriptionsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Subscription>;

    /**
     * 
     * @summary List subscriptions, optionally by customer
     * @param {SubscriptionsApiSubscriptionsListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    subscriptionsList(requestParameters?: SubscriptionsApiSubscriptionsListRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionList>;

}

/**
 * Request parameters for subscriptionsCancel operation in SubscriptionsApi.
 */
export interface SubscriptionsApiSubscriptionsCancelRequest {
    readonly id: string
}

/**
 * Request parameters for subscriptionsCreate operation in SubscriptionsApi.
 */
export interface SubscriptionsApiSubscriptionsCreateRequest {
    readonly createSubscriptionDto: CreateSubscriptionDto
}

/**
 * Request parameters for subscriptionsGet operation in SubscriptionsApi.
 */
export interface SubscriptionsApiSubscriptionsGetRequest {
    readonly id: string
}

/**
 * Request parameters for subscriptionsList operation in SubscriptionsApi.
 */
export interface SubscriptionsApiSubscriptionsListRequest {
    readonly customerId?: string

    readonly limit?: any

    readonly page?: any
}

/**
 * SubscriptionsApi - object-oriented interface
 */
export class SubscriptionsApi extends BaseAPI implements SubscriptionsApiInterface {
    /**
     * 
     * @summary Cancel a subscription immediately
     * @param {SubscriptionsApiSubscriptionsCancelRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public subscriptionsCancel(requestParameters: SubscriptionsApiSubscriptionsCancelRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).subscriptionsCancel(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a subscription (first charge confirmed by frontend)
     * @param {SubscriptionsApiSubscriptionsCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public subscriptionsCreate(requestParameters: SubscriptionsApiSubscriptionsCreateRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).subscriptionsCreate(requestParameters.createSubscriptionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a subscription
     * @param {SubscriptionsApiSubscriptionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public subscriptionsGet(requestParameters: SubscriptionsApiSubscriptionsGetRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).subscriptionsGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List subscriptions, optionally by customer
     * @param {SubscriptionsApiSubscriptionsListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public subscriptionsList(requestParameters: SubscriptionsApiSubscriptionsListRequest = {}, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).subscriptionsList(requestParameters.customerId, requestParameters.limit, requestParameters.page, options).then((request) => request(this.axios, this.basePath));
    }
}

