/* tslint:disable */
/* eslint-disable */
/**
 * Stripe Payment Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * WebhooksApi - axios parameter creator
 */
export const WebhooksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Verify → dedup → enqueue → 200. No business logic here: Stripe retries anything that doesn\'t get a 2xx within ~10s, so the heavy work happens in the background processor.
         * @param {string} stripeSignature 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        webhooksHandleStripeWebhook: async (stripeSignature: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stripeSignature' is not null or undefined
            assertParamExists('webhooksHandleStripeWebhook', 'stripeSignature', stripeSignature)
            const localVarPath = `/webhooks/stripe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            if (stripeSignature != null) {
                localVarHeaderParameter['stripe-signature'] = String(stripeSignature);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WebhooksApi - functional programming interface
 */
export const WebhooksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WebhooksApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Verify → dedup → enqueue → 200. No business logic here: Stripe retries anything that doesn\'t get a 2xx within ~10s, so the heavy work happens in the background processor.
         * @param {string} stripeSignature 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async webhooksHandleStripeWebhook(stripeSignature: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.webhooksHandleStripeWebhook(stripeSignature, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebhooksApi.webhooksHandleStripeWebhook']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WebhooksApi - factory interface
 */
export const WebhooksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WebhooksApiFp(configuration)
    return {
        /**
         * 
         * @summary Verify → dedup → enqueue → 200. No business logic here: Stripe retries anything that doesn\'t get a 2xx within ~10s, so the heavy work happens in the background processor.
         * @param {WebhooksApiWebhooksHandleStripeWebhookRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        webhooksHandleStripeWebhook(requestParameters: WebhooksApiWebhooksHandleStripeWebhookRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.webhooksHandleStripeWebhook(requestParameters.stripeSignature, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WebhooksApi - interface
 */
export interface WebhooksApiInterface {
    /**
     * 
     * @summary Verify → dedup → enqueue → 200. No business logic here: Stripe retries anything that doesn\'t get a 2xx within ~10s, so the heavy work happens in the background processor.
     * @param {WebhooksApiWebhooksHandleStripeWebhookRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    webhooksHandleStripeWebhook(requestParameters: WebhooksApiWebhooksHandleStripeWebhookRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * Request parameters for webhooksHandleStripeWebhook operation in WebhooksApi.
 */
export interface WebhooksApiWebhooksHandleStripeWebhookRequest {
    readonly stripeSignature: string
}

/**
 * WebhooksApi - object-oriented interface
 */
export class WebhooksApi extends BaseAPI implements WebhooksApiInterface {
    /**
     * 
     * @summary Verify → dedup → enqueue → 200. No business logic here: Stripe retries anything that doesn\'t get a 2xx within ~10s, so the heavy work happens in the background processor.
     * @param {WebhooksApiWebhooksHandleStripeWebhookRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public webhooksHandleStripeWebhook(requestParameters: WebhooksApiWebhooksHandleStripeWebhookRequest, options?: RawAxiosRequestConfig) {
        return WebhooksApiFp(this.configuration).webhooksHandleStripeWebhook(requestParameters.stripeSignature, options).then((request) => request(this.axios, this.basePath));
    }
}

